### ISSUE TITLE
yeah, no

### ISSUE THREAD

**Issue by lexysec** [prabaljainn/Linkedin_Connection_Bot#3]
https://github.com/prabaljainn/Linkedin-Connection-Bot/

https://www.linkedin.com/help/linkedin/answer/56347/prohibited-software-and-extensions?lang=en

LinkedIn is committed to keeping its members' data safe and its website free from fraud and abuse. In order to protect our members' data and our website, we don't permit the use of any third party software, including "crawlers", bots, browser plug-ins, or browser extensions (also called "add-ons"), that scrapes, modifies the appearance of, or automates activity on LinkedIn's website. Such tools violate the User Agreement, including, but not limited to, many of the "Don'ts" listed in Section 8.2:

Develop, support or use software, devices, scripts, robots, or any other means or processes (including crawlers, browser plugins and add-ons, or any other technology) to scrape the Services or otherwise copy profiles and other data from the Services;
Use bots or other automated methods to access the Services, add or download contacts, send or redirect messages;

**Comment by prabaljainn** [comment]
@lexysec what should i do now? delete this repo or make it private?
